[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["/server.js", "/package.json"]

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
features = ["node"]

[service]
port = 8080

# Logs
[logging]
level = "info" 