[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
features = ["node"]

[service]
port = 8080 