name: Expiration automatique des annonces

on:
  # DÉSACTIVÉ TEMPORAIREMENT - BUG DÉTECTÉ
  # schedule:
  #   - cron: '0 6 * * *'
  # Possibilité de déclencher manuellement seulement
  workflow_dispatch:

jobs:
  expire-announcements:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Expirer les annonces DodoPartage
        run: |
          echo "📅 Début de l'expiration quotidienne des annonces..."
          
          # Appel de l'API d'expiration
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions" \
            -H "X-Source: github-actions" \
            -d '{"source": "github-actions", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'"}' \
            https://web-production-7b738.up.railway.app/api/cron/expire-announcements)
          
          # Extraire le code HTTP et le body
          HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_CODE:/d')
          
          echo "📊 Code de réponse: $HTTP_CODE"
          echo "📋 Réponse: $BODY"
          
          # Vérifier le succès
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Expiration réussie !"
            
            # Parser les statistiques (optionnel)
            EXPIRED=$(echo "$BODY" | grep -o '"expired":[0-9]*' | cut -d: -f2 | head -1)
            REMAINING=$(echo "$BODY" | grep -o '"remaining_published":[0-9]*' | cut -d: -f2 | head -1)
            
            if [ ! -z "$EXPIRED" ] && [ ! -z "$REMAINING" ]; then
              echo "📈 Statistiques: $EXPIRED annonce(s) expirée(s), $REMAINING restante(s)"
            fi
          else
            echo "❌ Erreur lors de l'expiration (Code: $HTTP_CODE)"
            echo "💡 Réponse: $BODY"
            exit 1
          fi
          
          echo "🎉 Expiration quotidienne terminée avec succès !"

      - name: 📊 Résumé
        if: always()
        run: |
          echo "::notice title=Expiration DodoPartage::Expiration quotidienne exécutée à $(date -u)" 